
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class ConvertGroup : Luban.BeanBase
{
    public ConvertGroup(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
    }

    public static ConvertGroup DeserializeConvertGroup(JToken _buf)
    {
        return new ConvertGroup(_buf);
    }

    /// <summary>
    /// 兑换商人ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 兑换商人名称
    /// </summary>
    public readonly string Name;


    public const int __ID__ = 909038764;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

