
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Convert : Luban.BeanBase
{
    public Convert(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        ConvertItem = (string)_obj.GetValue("convertItem");
        Name = (string)_obj.GetValue("name");
        NeedItemList = (string)_obj.GetValue("needItemList");
        Parent = (int)_obj.GetValue("parent");
    }

    public static Convert DeserializeConvert(JToken _buf)
    {
        return new Convert(_buf);
    }

    /// <summary>
    /// 兑换ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 兑换的道具 (id, num)
    /// </summary>
    public readonly string ConvertItem;
    /// <summary>
    /// 兑换名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 兑换所需物品 (id, num)
    /// </summary>
    public readonly string NeedItemList;
    /// <summary>
    /// 属于哪个兑换商人
    /// </summary>
    public readonly int Parent;


    public const int __ID__ = -1678723693;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "convertItem:" + ConvertItem + ","
        + "name:" + Name + ","
        + "needItemList:" + NeedItemList + ","
        + "parent:" + Parent + ","
        + "}";
    }
}
}

