
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Enemy : Luban.BeanBase
{
    public Enemy(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        GlobalDefine = (string)_obj.GetValue("globalDefine");
    }

    public static Enemy DeserializeEnemy(JToken _buf)
    {
        return new Enemy(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 怪物名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 对应怪物名
    /// </summary>
    public readonly string GlobalDefine;


    public const int __ID__ = 67100520;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "globalDefine:" + GlobalDefine + ","
        + "}";
    }
}
}

