
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Item : Luban.BeanBase
{
    public Item(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        Price = (int)_obj.GetValue("price");
        Source = (string)_obj.GetValue("source");
        Usage = (string)_obj.GetValue("usage");
        Icon = (string)_obj.GetValue("icon");
        Type = (int)_obj.GetValue("type");
        Usable = (int)_obj.GetValue("usable");
        Level = (int)_obj.GetValue("level");
        Attack = (int)_obj.GetValue("attack");
        ArmorPenetration = (int)_obj.GetValue("armorPenetration");
        Defense = (int)_obj.GetValue("defense");
        DamageAvoidance = (int)_obj.GetValue("damageAvoidance");
        Hp = (int)_obj.GetValue("hp");
        Mp = (int)_obj.GetValue("mp");
    }

    public static Item DeserializeItem(JToken _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 来源
    /// </summary>
    public readonly string Source;
    /// <summary>
    /// 主要用途
    /// </summary>
    public readonly string Usage;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 可使用
    /// </summary>
    public readonly int Usable;
    /// <summary>
    /// 物品品阶
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 破甲值
    /// </summary>
    public readonly int ArmorPenetration;
    /// <summary>
    /// 防御力
    /// </summary>
    public readonly int Defense;
    /// <summary>
    /// 免伤值
    /// </summary>
    public readonly int DamageAvoidance;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 魔力值
    /// </summary>
    public readonly int Mp;


    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "source:" + Source + ","
        + "usage:" + Usage + ","
        + "icon:" + Icon + ","
        + "type:" + Type + ","
        + "usable:" + Usable + ","
        + "level:" + Level + ","
        + "attack:" + Attack + ","
        + "armorPenetration:" + ArmorPenetration + ","
        + "defense:" + Defense + ","
        + "damageAvoidance:" + DamageAvoidance + ","
        + "hp:" + Hp + ","
        + "mp:" + Mp + ","
        + "}";
    }
}
}

