
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Level : Luban.BeanBase
{
    public Level(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Exp = (int)_obj.GetValue("exp");
    }

    public static Level DeserializeLevel(JToken _buf)
    {
        return new Level(_buf);
    }

    /// <summary>
    /// 等级ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级经验
    /// </summary>
    public readonly int Exp;


    public const int __ID__ = 73313124;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "exp:" + Exp + ","
        + "}";
    }
}
}

