
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Store : Luban.BeanBase
{
    public Store(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        UnitPrice = (int)_obj.GetValue("unitPrice");
        CurrencyType = (int)_obj.GetValue("currencyType");
        Type = (int)_obj.GetValue("type");
    }

    public static Store DeserializeStore(JToken _buf)
    {
        return new Store(_buf);
    }

    /// <summary>
    /// 商品ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 商品单价
    /// </summary>
    public readonly int UnitPrice;
    /// <summary>
    /// 货币类型
    /// </summary>
    public readonly int CurrencyType;
    /// <summary>
    /// 商品类型
    /// </summary>
    public readonly int Type;


    public const int __ID__ = 80218305;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "unitPrice:" + UnitPrice + ","
        + "currencyType:" + CurrencyType + ","
        + "type:" + Type + ","
        + "}";
    }
}
}

