
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbTreasure TbTreasure {get; }
    public TbLevel TbLevel {get; }
    public TbEnemy TbEnemy {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbItem = new TbItem(loader("tbitem"));
        TbTreasure = new TbTreasure(loader("tbtreasure"));
        TbLevel = new TbLevel(loader("tblevel"));
        TbEnemy = new TbEnemy(loader("tbenemy"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbTreasure.ResolveRef(this);
        TbLevel.ResolveRef(this);
        TbEnemy.ResolveRef(this);
    }
}

}

