
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbConvert
{
    private readonly System.Collections.Generic.Dictionary<int, Convert> _dataMap;
    private readonly System.Collections.Generic.List<Convert> _dataList;
    
    public TbConvert(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Convert>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Convert>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Convert _v;
            _v = global::cfg.Convert.DeserializeConvert(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Convert> DataMap => _dataMap;
    public System.Collections.Generic.List<Convert> DataList => _dataList;

    public Convert GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Convert Get(int key) => _dataMap[key];
    public Convert this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

