
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbConvertGroup
{
    private readonly System.Collections.Generic.Dictionary<int, ConvertGroup> _dataMap;
    private readonly System.Collections.Generic.List<ConvertGroup> _dataList;
    
    public TbConvertGroup(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ConvertGroup>(_buf.Count);
        _dataList = new System.Collections.Generic.List<ConvertGroup>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            ConvertGroup _v;
            _v = global::cfg.ConvertGroup.DeserializeConvertGroup(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, ConvertGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<ConvertGroup> DataList => _dataList;

    public ConvertGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ConvertGroup Get(int key) => _dataMap[key];
    public ConvertGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

