
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbEnemy
{
    private readonly System.Collections.Generic.Dictionary<int, Enemy> _dataMap;
    private readonly System.Collections.Generic.List<Enemy> _dataList;
    
    public TbEnemy(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Enemy>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Enemy>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Enemy _v;
            _v = global::cfg.Enemy.DeserializeEnemy(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Enemy> DataMap => _dataMap;
    public System.Collections.Generic.List<Enemy> DataList => _dataList;

    public Enemy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Enemy Get(int key) => _dataMap[key];
    public Enemy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

