
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbStore
{
    private readonly System.Collections.Generic.Dictionary<int, Store> _dataMap;
    private readonly System.Collections.Generic.List<Store> _dataList;
    
    public TbStore(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Store>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Store>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Store _v;
            _v = global::cfg.Store.DeserializeStore(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Store> DataMap => _dataMap;
    public System.Collections.Generic.List<Store> DataList => _dataList;

    public Store GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Store Get(int key) => _dataMap[key];
    public Store this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

