
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbTreasure
{
    private readonly System.Collections.Generic.Dictionary<int, Treasure> _dataMap;
    private readonly System.Collections.Generic.List<Treasure> _dataList;
    
    public TbTreasure(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Treasure>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Treasure>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Treasure _v;
            _v = global::cfg.Treasure.DeserializeTreasure(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Treasure> DataMap => _dataMap;
    public System.Collections.Generic.List<Treasure> DataList => _dataList;

    public Treasure GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Treasure Get(int key) => _dataMap[key];
    public Treasure this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

