
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Treasure : Luban.BeanBase
{
    public Treasure(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Content = (string)_obj.GetValue("content");
        MinNum = (int)_obj.GetValue("minNum");
        MaxNum = (int)_obj.GetValue("maxNum");
        GlobalDefine = (string)_obj.GetValue("globalDefine");
    }

    public static Treasure DeserializeTreasure(JToken _buf)
    {
        return new Treasure(_buf);
    }

    /// <summary>
    /// 宝藏ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 宝藏名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 宝藏物品 (id, num, weight)
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 最小宝藏数
    /// </summary>
    public readonly int MinNum;
    /// <summary>
    /// 最大宝藏数
    /// </summary>
    public readonly int MaxNum;
    /// <summary>
    /// 对应宝箱名
    /// </summary>
    public readonly string GlobalDefine;


    public const int __ID__ = 1448052431;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "content:" + Content + ","
        + "minNum:" + MinNum + ","
        + "maxNum:" + MaxNum + ","
        + "globalDefine:" + GlobalDefine + ","
        + "}";
    }
}
}

